services:
  blog:
    build: .
    volumes:
      - .:/app
      # Exclude node_modules to use the container's version
      - /app/node_modules
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    networks:
      - cardjoy-blog-network-local
    # Remove the tail command since Dockerfile now runs yarn dev
    # this is needed for having astro server available
    stdin_open: true
    tty: true

networks:
  cardjoy-blog-network-local:
    name: cardjoy_blog_network_local
